# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: djc-core
  version: "1.3.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/djc_core-${{ version }}.tar.gz
  sha256: 73d5f42550d3fe8a776cc94778e889c65f8651fdb99ecf343d48a3547c6841b2

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }}  -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=1.8,<2.0

    - ${{ compiler("c") }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1,<2
  run:
    - python

tests:
  - python:
      imports:
        - djc_core
      pip_check: true

about:
  summary: Core library for django-components written in Rust.
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
    - crates/djc-safe-eval/submodules/ruff/crates/ruff_annotate_snippets/LICENSE-MIT
    - crates/djc-safe-eval/submodules/ruff/crates/ruff_annotate_snippets/LICENSE-APACHE
  homepage: https://github.com/django-components/djc-core

extra:
  recipe-maintainers:
    - rxm7706
